# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'Castable' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Castable

  pod 'AFNetworking', '~> 3.0'

  target 'CastableTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CastableUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
