<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'CAPodcast' => 'applications/podcasts/storage/CAPodcast.php',
    'CAPodcastITunesSource' => 'applications/podcasts/source/CAPodcastITunesSource.php',
    'CAPodcastListController' => 'applications/podcasts/controller/CAPodcastListController.php',
    'CAPodcastPHIDType' => 'applications/podcasts/phid/CAPodcastPHIDType.php',
    'CAPodcastQuery' => 'applications/podcasts/query/CAPodcastsQuery.php',
    'CAPodcastSearchConduitAPIMethod' => 'applications/podcasts/conduit/CAPodcastSearchConduitAPIMethod.php',
    'CAPodcastSearchEngine' => 'applications/podcasts/query/CAPodcastSearchEngine.php',
    'CAPodcastSource' => 'applications/podcasts/source/CAPodcastSource.php',
    'CAPodcastsApplication' => 'applications/podcasts/application/CAPodcastsApplication.php',
    'CAPodcastsController' => 'applications/podcasts/controller/CAPodcastsController.php',
    'CAPodcastsDAO' => 'applications/podcasts/storage/CAPodcastsDAO.php',
    'CAPodcastsImportSearchWorkflow' => 'applications/podcasts/management/CAPodcastsImportSearchWorkflow.php',
    'CAPodcastsImportWorkflow' => 'applications/podcasts/management/CAPodcastsImportWorkflow.php',
    'CAPodcastsManagementWorkflow' => 'applications/podcasts/management/CAPodcastsManagementWorkflow.php',
    'CAPodcastsPHIDType' => 'applications/podcasts/phid/CAPodcastsPHIDType.php',
    'CAPodcastsQuery' => 'applications/podcasts/query/CAPodcastQuery.php',
    'CAPodcastsSearchEngine' => 'applications/podcasts/query/CAPodcastsSearchEngine.php',
    'CASQLPatchList' => 'infrastructure/storage/CASQLPatchList.php',
  ),
  'function' => array(
    'ca_resolve_subpath' => 'infrastructure/filesystem/paths.php',
  ),
  'xmap' => array(
    'CAPodcast' => array(
      'CAPodcastsDAO',
      'PhabricatorPolicyInterface',
    ),
    'CAPodcastITunesSource' => 'CAPodcastSource',
    'CAPodcastListController' => 'CAPodcastsController',
    'CAPodcastPHIDType' => 'CAPodcastsPHIDType',
    'CAPodcastQuery' => 'CAPodcastsQuery',
    'CAPodcastSearchConduitAPIMethod' => 'PhabricatorSearchEngineAPIMethod',
    'CAPodcastSearchEngine' => 'CAPodcastsSearchEngine',
    'CAPodcastSource' => 'Phobject',
    'CAPodcastsApplication' => 'PhabricatorApplication',
    'CAPodcastsController' => 'PhabricatorController',
    'CAPodcastsDAO' => 'PhabricatorLiskDAO',
    'CAPodcastsImportSearchWorkflow' => 'CAPodcastsImportWorkflow',
    'CAPodcastsImportWorkflow' => 'CAPodcastsManagementWorkflow',
    'CAPodcastsManagementWorkflow' => 'PhabricatorManagementWorkflow',
    'CAPodcastsPHIDType' => 'PhabricatorPHIDType',
    'CAPodcastsQuery' => 'PhabricatorCursorPagedPolicyAwareQuery',
    'CAPodcastsSearchEngine' => 'PhabricatorApplicationSearchEngine',
    'CASQLPatchList' => 'PhabricatorSQLPatchList',
  ),
));
